---
- name: Install tomcat
  hosts: webservers
  become: true
  tasks:
  - name: Installing tomcat
    apt: 
      name: tomcat
      state: present
  - name: Starting tomcat
    service:
      name: tomcat
      state: started
      enabled: yes